LPanels = {
	["Default"] = {
	    --TOP
		{	name = "TOPInfoPanel",parent = "UIParent",
			anchor_to = "TOP",
			width = "100%",
			height = 15,
			y_off = -5,
			x_off = 0,
			--gradient = "V",
			bg_color = {0.1,0.1,0.1},
			--gradient_color = {0.1,0.1,0.1},
			bg_alpha = 0.6,
			--gradient_alpha = 0.8,
			strata = "BACKGROUND",
		},
		{	name = "TOPInfoPanelBOTTOMLine",parent = "TOPInfoPanel",
			anchor_to = "BOTTOM",
			width = "100%",
			height = 1,
			y_off = 0,
			x_off = 0,
			bg_color = "CLASS",
			bg_alpha = 0.7,
			strata = "BACKGROUND",
			
		},
		{	name = "TOPInfoPanelTOPLine",parent = "TOPInfoPanel",
			anchor_to = "TOP",
			width = "100%",
			height = 1,
			y_off = 0,
			x_off = 0,
			bg_color = "CLASS",
			bg_alpha = 0.7,
			strata = "BACKGROUND",
			
		},
		--BOTTOM
		{	name = "BOTTOMInfoPanel",parent = "UIParent",
			anchor_to = "BOTTOM",
			width = "100%",
			height = 15,
			y_off = 0,
			x_off = 0,
			--gradient = "V",
			bg_color = {0.1,0.1,0.1},
			--gradient_color = {0.1,0.1,0.1},
			bg_alpha = 0.6,
			--gradient_alpha = 0.8,
			strata = "BACKGROUND",
		},
		{	name = "BOTTOMInfoPanelBOTTOMLine",parent = "BOTTOMInfoPanel",
			anchor_to = "TOP",
			width = "100%",
			height = 1,
			y_off = 0,
			x_off = 0,
			bg_color = "CLASS",
			bg_alpha = 0.7,
			strata = "BACKGROUND",
		},
		--Shadow
		--Left 
		{ name = "Bottomleftshadow",parent = "UIParent",
		  anchor_to = "BOTTOMLEFT",
		  y_off = 15,
		  x_off = 0,
		  width = 320,
		  height = 177,
		  gradient = "H",
		  bg_color = {0.1,0.1,0.1},
		  bg_alpha = 0.6,
		  gradient_color = {0.1,0.1,0.1},
		  gradient_alpha = 0.0,
		  strata = "BACKGROUND",
		},
		{ name = "Bottomleftshadowline",parent = "Bottomleftshadow",
		  anchor_to = "BOTTOM",anchor_from = "TOP",
		  y_off = 0,
		  x_off = 0,
		  width = "100%",
		  height = 1,
		  gradient = "H",
		  bg_color = "CLASS",
		  bg_alpha = 0.6,
		  gradient_color = "CLASS",
		  gradient_alpha = 0.0,
		  strata = "BACKGROUND",
		  },
		  --right
		 { name = "Bottomrightshadow",parent = "UIParent",
		  anchor_to = "BOTTOMRIGHT",
		  y_off = 15,
		  x_off = 0,
		  width = 320,
		  height = 177,
		  gradient = "H",
		  bg_color = {0.1,0.1,0.1},
		  bg_alpha = 0.0,
		  gradient_color = {0.1,0.1,0.1},
		  gradient_alpha = 0.6,
		  strata = "BACKGROUND",
		},
		{ name = "Bottomrightshadowline",parent = "Bottomrightshadow",
		  anchor_to = "BOTTOM",anchor_from = "TOP",
		  y_off = 0,
		  x_off = 0,
		  width = "100%",
		  height = 1,
		  gradient = "H",
		  bg_color = "CLASS",
		  bg_alpha = 0.0,
		  gradient_color = "CLASS",
		  gradient_alpha = 0.6,
		  strata = "BACKGROUND",
		  },
		  
		  --raid panel
		  { name = "raid",parent = "Raid_Freebgrid",
		  anchor_to = "LEFT",
		  y_off = 0,
		  x_off = -7,
		  width = "170%",
		  height = "150%",
		  gradient = "H",
		  bg_color = {0.1,0.1,0.1},
		  bg_alpha = 0.6,
		  gradient_color = {0.1,0.1,0.1},
		  gradient_alpha = 0.0,
		  strata = "BACKGROUND",
		  require ="oUF_Freebgrid",
		 },
		 { name = "raidtopline",parent = "raid",
		  anchor_to = "BOTTOM",anchor_from = "TOP",
		  y_off = 0,
		  x_off = 0,
		  width = "100%",
		  height = 1,
		  gradient = "H",
		  bg_color = "CLASS",
		  bg_alpha = 0.6,
		  gradient_color = "CLASS",
		  gradient_alpha = 0.0,
		  strata = "BACKGROUND",
		  },
		  { name = "raidbottomline",parent = "raid",
		  anchor_to = "TOP",anchor_from = "BOTTOM",
		  y_off = 0,
		  x_off = 0,
		  width = "100%",
		  height = 1,
		  gradient = "H",
		  bg_color = "CLASS",
		  bg_alpha = 0.6,
		  gradient_color = "CLASS",
		  gradient_alpha = 0.0,
		  strata = "BACKGROUND",
		  },
		  
		  --CoolLine
		  { name = "CoolLinebg",parent = "CoolLine",
		    anchor_to = "CENTER", anchor_from = "CENTER",
			y_off = 0,x_off = 0,
			width = "100%",
			height = "100%",
			bg_color = {0.1,0.1,0.1},
			bg_alpha = 0.0,
			strata = "BACKGROUND",
			require ="CoolLine",
		  },
		  { name = "CoolLineSDL",parent = "CoolLinebg",
		    anchor_to = "RIGHT", anchor_from = "CENTER",
			y_off = 0,x_off = 0,
			width = "50%",
			height = "100%",
			gradient = "H",
			bg_color = {0.1,0.1,0.1},
		    bg_alpha = 0.0,
		    gradient_color = {0.1,0.1,0.1},
		    gradient_alpha = 0.6,
			strata = "BACKGROUND",
		  },
		  { name = "CoolLineSDR",parent = "CoolLinebg",
		    anchor_to = "LEFT", anchor_from = "CENTER",
			y_off = 0,x_off = 0,
			width = "50%",
			height = "100%",
			gradient = "H",
			bg_color = {0.1,0.1,0.1},
		    bg_alpha = 0.6,
		    gradient_color = {0.1,0.1,0.1},
		    gradient_alpha = 0.0,
			strata = "BACKGROUND",
		  },
		  { name = "CoolLineSDltop1",parent = "CoolLinebg",
		    anchor_to = "BOTTOMRIGHT", anchor_from = "TOP",
			y_off = 0,x_off = 0,
			width = "50%",
			height = 1,
			gradient = "H",
			bg_color = "CLASS",
		    bg_alpha = 0.0,
		    gradient_color = "CLASS",
		    gradient_alpha = 0.7,
			strata = "BACKGROUND",
		  },
		  { name = "CoolLineSDltop2",parent = "CoolLinebg",
		    anchor_to = "BOTTOMLEFT", anchor_from = "TOP",
			y_off = 0,x_off = 0,
			width = "50%",
			height = 1,
			gradient = "H",
			bg_color = "CLASS",
		    bg_alpha = 0.7,
		    gradient_color = "CLASS",
		    gradient_alpha = 0.0,
			strata = "BACKGROUND",
		  },
		  { name = "CoolLineSDlbottom1",parent = "CoolLinebg",
		    anchor_to = "TOPRIGHT", anchor_from = "BOTTOM",
			y_off = 0,x_off = 0,
			width = "50%",
			height = 1,
			gradient = "H",
			bg_color = "CLASS",
		    bg_alpha = 0.0,
		    gradient_color = "CLASS",
		    gradient_alpha = 0.7,
			strata = "BACKGROUND",
		  },
		  { name = "CoolLineSDlbottom2",parent = "CoolLinebg",
		    anchor_to = "TOPLEFT", anchor_from = "BOTTOM",
			y_off = 0,x_off = 0,
			width = "50%",
			height = 1,
			gradient = "H",
			bg_color = "CLASS",
		    bg_alpha = 0.7,
		    gradient_color = "CLASS",
		    gradient_alpha = 0.0,
			strata = "BACKGROUND",
		  },
	},
}
